workflows:
  ios_release:
    name: QuoteBot iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 15.4
      ios_signing:
        provisioning_profiles: []   # auto-managed
      vars:
        BUNDLE_ID: com.QuoteBot.quotebot
      groups:
        - app_store_connect         # your env var group with Issuer/KeyID/.p8
    cache:
      cache_paths:
        - ~/.pub-cache
        - $CM_BUILD_DIR/build
    scripts:
      - name: Flutter deps
        script: |
          flutter --version
          flutter pub get

      - name: Set unique build number
        script: |
          export BUILD_NUMBER=$(date +%s)
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV

      # Generate the iOS Xcode project BEFORE signing steps
      - name: Generate iOS project (no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Configure automatic signing (ASC API key)
        script: |
          keychain initialize
          app-store-connect set-api-key \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --key "$APP_STORE_CONNECT_PRIVATE_KEY"
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          # Now that ios/ exists, apply profiles to the Xcode project
          xcode-project use-profiles

      - name: Build signed IPA
        script: |
          # flutter build ipa will pick up the profiles configured above
          flutter build ipa --release --build-number=$BUILD_NUMBER
          ls -l build/ios/ipa || true

      - name: Upload to TestFlight
        script: |
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA produced"; exit 1
          fi
          app-store-connect publish --path "$IPA_PATH" --submit-to-testflight true
    artifacts:
      - build/ios/ipa/*.ipa
